export { authAPI } from './endpoints/auth'
export { shopsAPI } from './endpoints/shops'
export { skusAPI } from './endpoints/skus'
export { inventoryAPI } from './endpoints/inventory'
export { salesAPI } from './endpoints/sales'
export { auditAPI } from './endpoints/audit'
export { aiAPI } from './endpoints/ai'
export { alertsAPI } from './endpoints/alerts'
export { notificationsAPI } from './endpoints/notifications'
export { reportsAPI } from './endpoints/reports'
export { default as dashboardAPI } from './endpoints/dashboard'